### ISSUE TITLE
Week 18 Schedule

### ISSUE THREAD

**Issue by WiiExpertise** [bep713/madden-franchise-editor#31]
Is there a chance we could get Week 18 added to the Schedule Editor since Madden 22 now has the 17 game season implemented?

**Comment by bep713** [comment]
Added week 18 in the latest update a few months back.

**Comment by WiiExpertise** [comment]
Was the change only for M23? I don't see it on my M22 files. Using the latest version of the editor.

**Comment by matthewpanetta** [comment]
The change was made for both 23 and 22. Please send your M22 file and I can
test it out. It is working for M22 files for me

**Comment by WiiExpertise** [comment]
[STARTTODAYFILE.zip](https://github.com/bep713/madden-franchise-editor/files/10252644/STARTTODAYFILE.zip)

Here's one file that I tested.

**Comment by bep713** [comment]
My apologies, I was running with code that I hadn't released yet that added week 18. There are a few other things that I need to fix with the schedules to make them backward-compatible, but I can at least push a quick fix to show week 18 for now.

**Comment by bep713** [comment]
You should see it now with v4.5.3. Let me know!

**Comment by WiiExpertise** [comment]
Yep. Works great now. Thanks bep.
