### ISSUE TITLE
Error exporting to excel

### ISSUE THREAD

**Issue by huskereurocat** [bep713/madden-franchise-editor#36]
Every time that I export a file I get this error. The file saves and I have to open it from the explorer window or from inside excel when I open it. Excel is not open at the time of the export since in the last version when I exported a table it automatically opened in excel. How do I fix this going forward?  
![image](https://user-images.githubusercontent.com/52609668/158636776-acec2761-7ad4-43b2-8432-5bc160b558cc.png)

**Comment by bep713** [comment]
This issue was fixed in the latest update a few months back. Closing this issue
