### ISSUE TITLE
Cloud franchises??

### ISSUE THREAD

**Issue by aravmanchanda** [bep713/madden-franchise-editor#4]
Is there a way to edit cloud franchises or only offline franchises?

If not is there a way to convert cloud into offline?

Thanks

**Comment by bep713** [comment]
Hey,

This tool will work for offline franchises only as it looks at your locally saved files. I'm not sure of a way to convert a cloud franchise to offline.

You would be able to do it if you could get the entire franchise save from the cloud somehow...maybe through Cheat Engine? It would take a lot of work and looking into.

You most likely would not be able to pull a cloud franchise, edit it, and then put the edited version back on the cloud. At most, you'd be able to pull a cloud franchise and make it offline.
