### ISSUE TITLE
omaha xfactor

### ISSUE THREAD

**Issue by shogunreaper** [bep713/madden-franchise-editor#5]
can you add this to the editor?

**Comment by shogunreaper** [comment]
also "mossed", i don't see that one in there.

**Comment by bep713** [comment]
Hey, yeah I will add these in the next update. I see the issue, should hopefully be an easy fix.

**Comment by bep713** [comment]
Omaha has been added. Looks like the game has added checks so you can't add the ability to any player with any overall.

The ability can only be added if you can add it in the game.
