### ISSUE TITLE
Stadium and City tables are blank. 

### ISSUE THREAD

**Issue by Hakuyuyuyu** [bep713/madden-franchise-editor#55]
Those tables can be parsed but there is no information on those screens that are displayed, making it impossible to modify stadium ratings and seating capacities or city details (income tax, market size).

**Comment by bep713** [comment]
@Hakuyuyuyu looks like there isn't any data in those tables. (Tools -> Export Raw Data) They're likely pulling this data from the FTC files now, but hard to say for sure. Either way, the editor appears to be working correctly.
