### ISSUE TITLE
In the 'FOF' franchise save file 144-Player section, I couldn't find the 'FOF' player. Where should I find it?

### ISSUE THREAD

**Issue by PrimeTimerer** [bep713/madden-franchise-editor#7]
I finished the story mode of 'FOF'.
But in the 144-Player section of the Franchise Editor,
I couldn't find the 'FOF' player.
Please allow me to edit the "FOF" player.

**Comment by bep713** [comment]
This might be due to how Madden saves things. The FOF player probably doesn't exist in the Player table, you'll have to find a separate table with that data. I don't know where else it would be - but I'm fairly confident this is not an issue with the editor.
