### ISSUE TITLE
is it possible to change players from being retired

### ISSUE THREAD

**Issue by tbb429** [bep713/madden-franchise-editor#8]
is it possible to bring back retired players, and if so what are the steps. i've tried to poke around with the editor to do this but nothing seems to work

**Comment by bep713** [comment]
It would all depend on how Madden handles retired players. I know there is a field with a player status that shows Retired, but does Madden remove the player after the year or keep all of the retired players sitting there? If so, I doubt just changing the enum will solve the problem - you'd probably need to edit other tables as well to add the player into the FA pool or back on a team.

**Comment by bep713** [comment]
Closing this question due to inactivity
